apiVersion: v1
kind: Service
metadata:
  name: apuestas-service-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: apuestas-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005